#!/bin/bash

function main () 
{
	echo Warning this will reset Chrome NewTab settings
    echo \#\#\# Running \#\#\#
	
	defaults write com.google.Chrome HomepageIsNewTabPage -bool false
	defaults write com.google.Chrome NewTabPageLocation -string “https://www.google.com/”
	defaults write com.google.Chrome HomepageLocation -string “https://www.google.com/”
	defaults delete com.google.Chrome DefaultSearchProviderSearchURL
	defaults delete com.google.Chrome DefaultSearchProviderNewTabURL
	defaults delete com.google.Chrome DefaultSearchProviderName
	
	echo Please restart Chrome

    exit 0
}

main
