#!/bin/bash

disk=0

function main ()
{

   echo \#\#\# Mounting EFI Partition \#\#\#

   diskutil list
   
   echo Mounting /dev/disk"$disk"s1

   sudo mkdir /Volumes/EFI
   sudo mount -t msdos /dev/disk"$disk"s1 /Volumes/EFI

   cd /Volumes/EFI/EFI
   open .

   echo \#\#\# Done \#\#\#

   exit 0
}

main
