#!/bin/bash

function main () 
{
    echo \#\#\# Running \#\#\#
    
    echo Ensure that you booted into recovery and in the terminal you ran \'csrutil disable\' before running this script. If not exit now.
    read -n 1 -s -r -p "Press any key to continue"
    
    echo Change \<key\>com.apple.ManagedClient.enroll\</key\>
    echo \<true/\>
    
    echo  to 
    
    echo Change \<key\>com.apple.ManagedClient.enroll\</key\>
    echo    \<false/\>
    
    read -n 1 -s -r -p "Press any key to continue"
    
    sudo nano /System/Library/CoreServices/ManagedClient.app/Contents/Resources/com.apple.ManagedClient.enroll.plist

    exit 0
}

main
